name: CD

on:
    push:
        branches:
            - main

jobs:
    cd:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v3

         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
               java-version: '17'
               distribution: 'zulu'

         - name: Deploy For EC2 # EC2 접속
           uses: appleboy/ssh-action@master
           with:
               host: ${{ secrets.EC2_HOST }}
               username: ${{ secrets.EC2_USERNAME }}
               key: ${{ secrets.EC2_SSH_KEY }}
               port: ${{ secrets.EC2_SSH_PORT }}
               script: |
                     cd sfe
                     git clone https://github.com/Survival-From-Epidemic/Survival-From-Epidemic-Backend.git
                     cd Survival-From-Epidemic-Backend/
                     mkdir -p src/main/resources
                     echo "${{ secrets.MAIN_APPLICATION }}" | base64 --decode > src/main/resources/application.yml
                     touch .env
                     echo "${{ secrets.ENV }}" >> .env
                     docker-compose up -d