name: CD

on:
    push:
        branches:
            - main

jobs:
    cd:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v3

         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
               java-version: '17'
               distribution: 'zulu'

         - name: Set up .jar
           run: ./gradlew bootJar

         - name: Publish to Registry
           uses: elgohr/Publish-Docker-Github-Action@v5
           with:
               name: ${{ secrets.DOCKER_REPOSITORY }}
               username: ${{ secrets.DOCKER_USERNAME }}
               password: ${{ secrets.DOCKER_PASSWORD }}

         - name: Deploy For EC2 # EC2 ssh 접속
           uses: appleboy/ssh-action@master
           with:
               host: ${{ secrets.EC2_HOST }}
               port: ${{ secrets.EC2_SSH_PORT }}
               username: ${{ secrets.EC2_USERNAME }}
               key: ${{ secrets.EC2_SSH_KEY }}
               script: |
                     cd sfe
                     docker pull ${{ secrets.DOCKER_REPOSITORY }}
                     docker rm -f sfe-server
                     docker run -dp ${SPRING_HOST_PORT}:${SPRING_CONTAINER_PORT} --name sfe-server --env-file .env ${{ secrets.DOCKER_REPOSITORY }}