name: CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'zulu'

    - name: Run ktlint
      run: ./gradlew ktlintCheck

    - name: Create application.yml
      run: |
         mkdir -p src/main/resources
         echo "${{ secrets.APPLICATION }}" | base64 --decode > src/main/resources/application.yml

    - name: Set up MySQL
      uses: samin/mysql-action@v1.1
      with:
          character set server: 'utf8'
          mysql database: 'sfe'
          mysql user: 'root'
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
          arguments: build