name: CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'zulu'

    - name: Run ktlint
      run: ./gradlew ktlintCheck

    - name: Set up application.yml
      run: |
         mkdir -p src/main/resources
         echo "${{ secrets.MAIN_APPLICATION }}" | base64 --decode > src/main/resources/application.yml
         mkdir -p src/test/resources
         echo "${{ secrets.TEST_APPLICATION }}" | base64 --decode > src/test/resources/application.yml

    - name: run test
      run: ./gradlew test

    - name: run build
      run: ./gradlew clean build -x test