name: Lint

on: [push, pull_request]

jobs:
    ktlint:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
          with:
              fetch-depth: 0

        - name: ktlint
          uses: ScaCap/action-ktlint@master
          with:
              github_token: ${{ secrets.github_token }}
              reporter: github-pr-check