name: Lint

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    ktlint:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: ktlint
          run: ./gradlew ktlintCheck